### ISSUE TITLE
Started getting error message after upgrade to 0.6.2

### ISSUE THREAD

**Issue by GasTurbineMan** [biddster/node-red-contrib-time-range-switch#25]
Upgraded contrib-time-range-switch to 0.6.2 via Node-Red "manage palette" and restarted Node-Red.  Now getting the following error message in the Debug window:

"TypeError: moment.twix is not a function"

I get this error message every time a message is sent to the "switch" node.  Never got this message on prior version.

**Comment by dazrave** [comment]
+1

**Quick Fix**
For now, I downgraded by stopping node-red and then ran 
`npm install node-red-contrib-time-range-switch@0.6.1` 
which seemed to fix things.

**Comment by biddster** [comment]
Thanks for the reports. Downgrade is sensible until I get to the bottom of it.

**Comment by recklessnl** [comment]
Also getting this error. Your latest version of github does fix it. Perhaps push that out as version 0.6.3 to the public?

**Comment by biddster** [comment]
That's the plan @recklessnl, I've just got it in test here before releasing it. I always run the next release on my home setup before releasing to the public.

**Comment by biddster** [comment]
0.6.3 released with what I hope is the fix. Please let me know and reopen if necessary.

**Comment by GasTurbineMan** [comment]
6.3 appears to have resolved the issue.  Many thanks for the prompt action.
